version: "3.9"

name: "pull-ups-project"

services:
    python:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./:/app
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=db
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgis/postgis:14-3.3-alpine
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 1s
            timeout: 1s
            retries: 30
volumes:
    postgres-data:
