# Generated by Django 4.2.1 on 2023-11-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievementtype_achievement_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievementtype')),
            ],
            options={
                'unique_together': {('type', 'threshold')},
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.achievementimage'),
        ),
    ]
