# Generated by Django 4.2.1 on 2023-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars", "0002_alter_address_options_alter_bars_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bars",
            name="tags",
            field=models.ManyToManyField(to="tag.tag"),
        ),
    ]
