# Generated by Django 4.2.1 on 2023-06-01 17:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_remove_bars_latitude_remove_bars_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
