# Generated by Django 4.2.1 on 2023-08-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_alter_bars_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bars.address'),
        ),
    ]
