# Generated by Django 4.2.1 on 2024-03-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0007_remove_bars_address_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bars',
            name='tags',
        ),
    ]
