# Generated by Django 4.2.1 on 2024-03-17 05:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pullupbars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pullupbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_grounds', to='pullupbars.pullupbars')),
            ],
            options={
                'verbose_name': 'Training Ground',
                'verbose_name_plural': 'Training Grounds',
            },
        ),
    ]
