# Generated by Django 4.2.1 on 2024-03-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipstations', '0001_initial'),
        ('pullupbars', '0002_remove_pullupbars_location'),
        ('training_ground', '0002_alter_trainingground_pullupbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingground',
            name='dipstation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_ground', to='dipstations.dipstation'),
        ),
        migrations.AlterField(
            model_name='trainingground',
            name='pullupbar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_ground', to='pullupbars.pullupbars'),
        ),
    ]
