# Generated by Django 4.2.1 on 2024-03-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0008_remove_bars_tags'),
        ('tag', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
