# Generated by Django 4.2.1 on 2023-07-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_alter_bars_location'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bars.bars'),
        ),
    ]
