# Generated by Django 4.2.1 on 2024-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullupbars', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_pullupbars',
            field=models.ManyToManyField(blank=True, to='pullupbars.pullupbars'),
        ),
    ]
