# Generated by Django 4.2.1 on 2024-03-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_ground', '0001_initial'),
        ('user', '0002_user_favorite_pullupbars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_training_grounds',
            field=models.ManyToManyField(blank=True, to='training_ground.trainingground'),
        ),
    ]
