# Generated by Django 4.2.1 on 2023-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_alter_bars_location'),
        ('user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_bars',
            field=models.ManyToManyField(to='bars.bars'),
        ),
    ]
