# Generated by Django 4.2.1 on 2024-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_favorite_training_grounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_pullupbars',
        ),
    ]
