# Generated by Django 4.2.1 on 2024-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_squashed_0008_remove_bars_tags'),
        ('user', '0001_squashed_0003_user_favorite_bars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_bars',
            field=models.ManyToManyField(blank=True, to='bars.bars'),
        ),
    ]
