# Generated by Django 4.2.1 on 2024-03-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipstations', '0002_rename_dipstation_dipstations'),
        ('counter', '0002_dipcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipcounter',
            name='dipstation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dip_counter', to='dipstations.dipstations'),
            preserve_default=False,
        ),
    ]
